steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      addToPath: true
      architecture: "x64"

  - bash: |
      cd src
      pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
  
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/src"
      includeRootFolder: false
      archiveFile: "$(Build.SourcesDirectory)/deployment/functions/build$(Build.BuildId).zip"
  
  - task: CopyFiles@2
    displayName: "Copy deployment template/pipeline definitions and scripts to artifacts"
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/deployment"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/deployment"
      Contents: '**'

  - task: PublishPipelineArtifact@0
    displayName: "Publish pipeline artifacts"
    inputs:
      artifactName: "drop"
      targetPath: "$(Build.ArtifactStagingDirectory)"